[project]
name = "osrs-dump-scanner"
version = "0.1.0"
dependencies = [
    "httpx",
    "pandas",
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]
